<p><strong>Подвиг 3.</strong> В программе объявлена функция:</p>

<pre><code>def get_number(x):
    try:
        return int(x)
    except:
        try:
            return float(x)
        except:
            return x</code></pre>

<p>И вызывается со следующими аргументами:</p>

<pre><code>res_1 = get_number('-5')
res_2 = get_number('5.78')
res_3 = get_number('8(912)000-000-00')</code></pre>

<p>Выберите все верные утверждения, связанные с этой программой.</p>